import type { Metadata } from 'next';
import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import { dark } from '@clerk/themes';
import { ThemeProvider } from '@/components/theme-provider';
import { Toaster } from 'react-hot-toast'

export const metadata: Metadata = {
  title: 'FORMS.AI',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
        variables: {
          fontFamily: 'Roboto, sans-serif',
        },
        elements: {
          '*': 'font-roboto',
          profileNavbar: 'font-roboto',
          profilePage: 'font-roboto',
        },
      }}
    >
      <html lang='en' suppressHydrationWarning>
        <body className={`antialiased`}>
          <ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange>
          {/* <ThemeProvider> */}
            {children}
            <Toaster />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
